### PR TITLE
File writing renaming

### PR DESCRIPTION
**Pull request by MdSufiyan005**

### CODE REVIEW

**Review by cflynn3 — COMMENTED** [review]
These changes all look good, great first PR! Please can you remove the whitespace that ruff is complaining about, and I'll be able to merge it in :-)
You can run the ruff checks on your local machine as well, as detailed in the documentation.

**Comment by MdSufiyan005** [comment]
Sure

**Comment by MdSufiyan005** [comment]
why did it failed ?

**Comment by cflynn3** [comment]
> why did it failed ?

https://github.com/bp/ResSimpy/actions/runs/6198961181/job/16831516439?pr=182

This time the static analysis failed due to an indent not being quite right. Should be another simple fix. You're able to run that check on your local using the flake8 command.

**Comment by MdSufiyan005** [comment]
one_sec

on my machine, it is not showing me " Process completed with exit code 1. "

**Comment by MdSufiyan005** [comment]
and the indentation error that is being prompted, has exactly the same indentation in the main program file.

**Comment by cflynn3** [comment]
> and the indentation error that is being prompted, has exactly the same indentation in the main program file.

It was one space different, which was causing the check to fail. I've pushed changes for you that should fix this.

**Review by cflynn3 — APPROVED** [review]
Looks good to me.

**Pull request merged**
